---
deployment:
 tasks:
 - export DEPLOYPATH=/home/user/public_html/
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R images $DEPLOYPATH
 - /bin/cp career.php $DEPLOYPATH
 - /bin/cp certification.php $DEPLOYPATH
 - /bin/cp education.php $DEPLOYPATH
 - /bin/cp include.php $DEPLOYPATH
 - /bin/cp index.php $DEPLOYPATH
 - /bin/cp privacy.php $DEPLOYPATH
 - /bin/cp projects.php $DEPLOYPATH
 - /bin/cp support.php $DEPLOYPATH